<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hw_devices" nsURI="http://www.example.org/hw_devices" nsPrefix="hw_devices">
  <eClassifiers xsi:type="ecore:EClass" name="Device">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vcc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pins" upperBound="-1" eType="#//Pin"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Computational" eSuperTypes="#//Device">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connected_devices" upperBound="-1"
        eType="#//D2DConnection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpu_family" eType="#//CpuFamily"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ram" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_freq" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fpu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dma" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wifi" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ble" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ethernet" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rtc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usb2s" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usb3s" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="i2cs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="spis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uarts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pwms" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="external_memory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="battery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adcs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NonComputational" eSuperTypes="#//Device">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//DeviceType"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeviceType" instanceTypeName="DeviceType">
    <eLiterals name="SENSOR"/>
    <eLiterals name="ACTUATOR" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PowerPin" eSuperTypes="#//Pin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="function" eType="#//PowerType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IOPinFunction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//IOType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hw_port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IOPin" eSuperTypes="#//Pin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IOType" instanceTypeName="IO">
    <eLiterals name="GPIO_INPUT"/>
    <eLiterals name="GPIO_OUTPUT" value="1"/>
    <eLiterals name="GPIO_BOTH" value="2"/>
    <eLiterals name="I2C_SDA" value="3"/>
    <eLiterals name="I2C_SCL" value="4"/>
    <eLiterals name="PWM" value="5"/>
    <eLiterals name="GPCLK" value="6"/>
    <eLiterals name="UART_TX" value="7"/>
    <eLiterals name="UART_RX" value="8"/>
    <eLiterals name="SPI_MOSI" value="9"/>
    <eLiterals name="SPI_MISO" value="10"/>
    <eLiterals name="SPI_SCLK" value="11"/>
    <eLiterals name="SPI_CE" value="12"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PowerType" instanceTypeName="Power">
    <eLiterals name="GND"/>
    <eLiterals name="POWER_3V3" value="1"/>
    <eLiterals name="POWER_5V" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="D2DConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="device" lowerBound="1"
        eType="#//NonComputational"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pin_connections" lowerBound="1"
        upperBound="-1" eType="#//Pin2PinConnection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pin2PinConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="comp_pin" lowerBound="1"
        eType="#//Pin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="non_comp_pin" lowerBound="1"
        eType="#//Pin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CpuFamily">
    <eLiterals name="ARM_CORTEX_M"/>
    <eLiterals name="AVR" value="1"/>
    <eLiterals name="MSP430" value="2"/>
    <eLiterals name="MIPS" value="3"/>
    <eLiterals name="EFM32" value="4"/>
    <eLiterals name="ARM_CORTEX_A" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigitalPin" eSuperTypes="#//IOPin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functions" lowerBound="1"
        upperBound="-1" eType="#//IOPinFunction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnalogPin" eSuperTypes="#//IOPin"/>
</ecore:EPackage>
