<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hw_devices" nsURI="http://www.example.org/hw_devices" nsPrefix="hw_devices">
  <eClassifiers xsi:type="ecore:EClass" name="Device">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vcc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pins" upperBound="-1" eType="#//Pin"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operating_voltage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hw_interfaces" upperBound="-1"
        eType="#//HwInterface" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="network" upperBound="-1"
        eType="#//Network" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bluetooth" eType="#//Bluetooth"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Board" eSuperTypes="#//Device">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rtc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="battery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dma" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cpu" lowerBound="1" eType="#//CPU"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memory" lowerBound="1"
        eType="#//Memory" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="os" eType="#//OSType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Peripheral" eSuperTypes="#//Device">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PeripheralType"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PeripheralType" instanceTypeName="DeviceType">
    <eLiterals name="SENSOR"/>
    <eLiterals name="ACTUATOR" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PowerPin" eSuperTypes="#//Pin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PowerType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IOPin" eSuperTypes="#//Pin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="CpuFamily">
    <eLiterals name="ARM_CORTEX_M"/>
    <eLiterals name="AVR" value="1"/>
    <eLiterals name="MSP430" value="2"/>
    <eLiterals name="MIPS" value="3"/>
    <eLiterals name="EFM32" value="4"/>
    <eLiterals name="ARM_CORTEX_A" value="5"/>
    <eLiterals name="ESP8266" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigitalPin" eSuperTypes="#//IOPin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnalogPin" eSuperTypes="#//IOPin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vmax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HwInterface" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_connections" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="num_connections" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="I2C" eSuperTypes="#//HwInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sda" lowerBound="1" eType="#//DigitalPin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scl" lowerBound="1" eType="#//DigitalPin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bus" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="is_master" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_master_cons" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1008"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SPI" eSuperTypes="#//HwInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="miso" lowerBound="1" eType="#//DigitalPin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ce" upperBound="-1" eType="#//DigitalPin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mosi" lowerBound="1" eType="#//DigitalPin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sclk" lowerBound="1" eType="#//DigitalPin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bus" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="is_master" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_master_cons" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UART" eSuperTypes="#//HwInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rx" lowerBound="1" eType="#//DigitalPin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tx" lowerBound="1" eType="#//DigitalPin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bus" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PWM" eSuperTypes="#//HwInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pin" lowerBound="1" eType="#//DigitalPin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="USB" eSuperTypes="#//HwInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//USBType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bus" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GPIOType" instanceTypeName="GPIOType">
    <eLiterals name="INPUT"/>
    <eLiterals name="OUTPUT" value="1"/>
    <eLiterals name="BOTH" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GPIO" eSuperTypes="#//HwInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//GPIOType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pin" lowerBound="1" eType="#//IOPin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADC" eSuperTypes="#//HwInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pin" lowerBound="1" eType="#//AnalogPin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Memory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ram" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="external_memory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CPU">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpu_family" eType="#//CpuFamily"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_freq" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fpu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="USBType" instanceTypeName="USBType">
    <eLiterals name="USB2"/>
    <eLiterals name="USB3" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B2PConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hw_connections" upperBound="-1"
        eType="#//HwInt2HwInt" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="power_connections" upperBound="-1"
        eType="#//Power2Power" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="board" lowerBound="1" eType="#//Board"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="peripheral" lowerBound="1"
        eType="#//Peripheral"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="peripheral_impl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="com_endpoint" lowerBound="1"
        eType="#//ComEndpoint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HwInt2HwInt" abstract="true" eSuperTypes="#//Hw2Hw"/>
  <eClassifiers xsi:type="ecore:EClass" name="Power2Power" eSuperTypes="#//Hw2Hw">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pin_1" lowerBound="1" eType="#//PowerPin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pin_2" lowerBound="1" eType="#//PowerPin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hw2Hw" abstract="true" interface="true">
    <eOperations name="connect"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OSType" instanceTypeName="OS">
    <eLiterals name="RASPBIAN"/>
    <eLiterals name="RIOT" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Usb2Usb" eSuperTypes="#//HwInt2HwInt"/>
  <eClassifiers xsi:type="ecore:EClass" name="Adc2Adc" eSuperTypes="#//HwInt2HwInt"/>
  <eClassifiers xsi:type="ecore:EClass" name="I2c2I2c" eSuperTypes="#//HwInt2HwInt">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="slave_address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hwint_1" lowerBound="1"
        eType="#//I2C"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hwint_2" lowerBound="1"
        eType="#//I2C"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Spi2Spi" eSuperTypes="#//HwInt2HwInt">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ce_index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hwint_1" lowerBound="1"
        eType="#//SPI"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hwint_2" lowerBound="1"
        eType="#//SPI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Uart2Uart" eSuperTypes="#//HwInt2HwInt">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baudrate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hwint_1" lowerBound="1"
        eType="#//UART"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hwint_2" lowerBound="1"
        eType="#//UART"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pwm2Pwm" eSuperTypes="#//HwInt2HwInt">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hwint_1" lowerBound="1"
        eType="#//PWM"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hwint_2" lowerBound="1"
        eType="#//PWM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gpio2Gpio" eSuperTypes="#//HwInt2HwInt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hwint_1" lowerBound="1"
        eType="#//GPIO"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hwint_2" lowerBound="1"
        eType="#//GPIO"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Network" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wifi" eSuperTypes="#//Network">
    <eStructuralFeatures xsi:type="ecore:EReference" name="freqs" lowerBound="1" upperBound="-1"
        eType="#//WifiFreq" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ethernet" eSuperTypes="#//Network"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bluetooth">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PowerType" instanceTypeName="PowerType">
    <eLiterals name="GND"/>
    <eLiterals name="Power3V3" value="1"/>
    <eLiterals name="Power5V" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WifiFreq">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="freq" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComEndpoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topic_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conn_params" lowerBound="1"
        eType="#//ConnParams" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="msg" lowerBound="1" eType="#//Msg"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnParams">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="host" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PerDeviceDataType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SensorDataType" eSuperTypes="#//PerDeviceDataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SensorTypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActuatorDataType" eSuperTypes="#//PerDeviceDataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ActuatorTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Msg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="msg_entries" lowerBound="1"
        upperBound="-1" eType="#//PerDeviceDataType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SensorTypes">
    <eLiterals name="DISTANCE"/>
    <eLiterals name="TEMPERATURE" value="1"/>
    <eLiterals name="HUMIDITY" value="1"/>
    <eLiterals name="GAS" value="1"/>
    <eLiterals name="ACCELEROMETER" value="1"/>
    <eLiterals name="MAGNETOMETER" value="1"/>
    <eLiterals name="GYROSCOPE" value="1"/>
    <eLiterals name="IMU" value="1"/>
    <eLiterals name="LINE_FOLLOWER" value="1"/>
    <eLiterals name="BUTTON" value="1"/>
    <eLiterals name="BUTTON_ARRAY" value="1"/>
    <eLiterals name="ENV" value="11"/>
    <eLiterals name="PRESSURE" value="12"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActuatorTypes">
    <eLiterals name="MOTOR_CONTROLLER"/>
    <eLiterals name="LED" value="1"/>
    <eLiterals name="LEDS_CONTROLLER" value="1"/>
    <eLiterals name="SERVO" value="1"/>
    <eLiterals name="SERVO_CONTROLLER" value="1"/>
  </eClassifiers>
</ecore:EPackage>
